# python structure for L-Galaxies 2020 (Yates+23) with the LITE_OUTPUT switch on and DETAILED_DUST switch off:
import numpy
LGalaxiesStruct = numpy.dtype([
('Type',numpy.int32),
('HaloIndex',numpy.int32),
('HaloM_Crit200',numpy.float32),
('SnapNum',numpy.int32),
('LookBackTimeToSnap',numpy.float32),
('CentralMvir',numpy.float32),
('CentralRvir',numpy.float32),
('DistanceToCentralGal',numpy.float32,(3,)),
('Pos',numpy.float32,(3,)),
('Vel',numpy.float32,(3,)),
('Len',numpy.int32),
('Mvir',numpy.float32),
('Rvir',numpy.float32),
('Vvir',numpy.float32),
('Vmax',numpy.float32),
('ColdGasSpin',numpy.float32,(3,)),
('DiskSpin',numpy.float32,(3,)),
('ColdGas',numpy.float32),
('ColdGasRings',numpy.float32,(12,)),
('H2fraction',numpy.float32),
('H2fractionRings',numpy.float32,(12,)),
('StellarMass',numpy.float32),
('DiskMass',numpy.float32),
('BulgeMass',numpy.float32),
('DiskMassRings',numpy.float32,(12,)),
('BulgeMassRings',numpy.float32,(12,)),
('HotGas',numpy.float32),
('EjectedMass',numpy.float32),
('BlackHoleMass',numpy.float32),
('ICM',numpy.float32),
('MetalsColdGas',numpy.float32,(3,)),
('MetalsColdGasRings',numpy.float32,(12,3)),
('MetalsStellarMass',numpy.float32,(3,)),
('MetalsDiskMass',numpy.float32,(3,)),
('MetalsBulgeMass',numpy.float32,(3,)),
('MetalsDiskMassRings',numpy.float32,(12,3)),
('MetalsBulgeMassRings',numpy.float32,(12,3)),
('MetalsHotGas',numpy.float32,(3,)),
('MetalsEjectedMass',numpy.float32,(3,)),
('MetalsICM',numpy.float32,(3,)),
('DiskSNIIRate',numpy.float32),
('BulgeSNIIRate',numpy.float32),
('ICMSNIIRate',numpy.float32),
('DiskSNIaRate',numpy.float32),
('BulgeSNIaRate',numpy.float32),
('ICMSNIaRate',numpy.float32),
('Sfr',numpy.float32),
('SfrInst',numpy.float32),
('SfrRings',numpy.float32,(12,)),
('SfrInstRings',numpy.float32,(12,)),
('SfrBulge',numpy.float32),
('BulgeSize',numpy.float32),
('DiskRadius',numpy.float32),
('ColdGasRadius',numpy.float32),
('StellarHalfMassRadius',numpy.float32),
('MassWeightAge',numpy.float32),
('DiskMass_elements',numpy.float32,(11,)),
('BulgeMass_elements',numpy.float32,(11,)),
('DiskMassRings_elements',numpy.float32,(12,11)),
('BulgeMassRings_elements',numpy.float32,(12,11)),
('ColdGas_elements',numpy.float32,(11,)),
('ColdGasRings_elements',numpy.float32,(12,11)),
('HotGas_elements',numpy.float32,(11,)),
('ICM_elements',numpy.float32,(11,)),
('EjectedMass_elements',numpy.float32,(11,)),
#('ending','i4')
])
properties_used = {}
for el in LGalaxiesStruct.names:
 	properties_used[el] = True
 